# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3df7a5410f238931f46b8399250fc87e"
application_url = "https://cook-schedule-levitra-glucose.trycloudflare.com"
embedded = true
name = "CSV Sync Inventory (Fosen)"
handle = "csv-sync-inventory-fosen"

[build]
include_config_on_deploy = true
dev_store_url = "nextgen-teststore.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,write_inventory,write_products"

[auth]
redirect_urls = [
  "https://cook-schedule-levitra-glucose.trycloudflare.com/auth/callback",
  "https://cook-schedule-levitra-glucose.trycloudflare.com/auth/shopify/callback",
  "https://cook-schedule-levitra-glucose.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
