# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8860213a934138d0cbc414bbe2712de5"
application_url = "https://agreed-minister-started-io.trycloudflare.com"
embedded = true
name = "CSV Inventory Sync "
handle = "csv-product-sync"

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,write_inventory,write_products"

[auth]
redirect_urls = [
  "https://agreed-minister-started-io.trycloudflare.com/auth/callback",
  "https://agreed-minister-started-io.trycloudflare.com/auth/shopify/callback",
  "https://agreed-minister-started-io.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "nextgen-teststore.myshopify.com"
automatically_update_urls_on_dev = true
